version: 2

models:
  - name: stg_financial_transactions
    description: Staging view over `staging.financial_transactions` with standardized fields.
    columns:
      - name: transaction_id
        tests:
          - not_null
          - unique
      - name: currency
        tests:
          - accepted_values:
              values: ["SEK", "EUR", "USD", "GBP", "NOK", "DKK"]
      - name: status
        tests:
          - accepted_values:
              values: ["BOOKED", "PENDING", "FAILED"]


